//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp10 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResIngles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResIngles() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp10.ResIngles", typeof(ResIngles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        internal static string Evento_btnAceptar {
            get {
                return ResourceManager.GetString("Evento_btnAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In process.
        /// </summary>
        internal static string Evento_btnEnProceso {
            get {
                return ResourceManager.GetString("Evento_btnEnProceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalized.
        /// </summary>
        internal static string Evento_btnFinalizados {
            get {
                return ResourceManager.GetString("Evento_btnFinalizados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To start.
        /// </summary>
        internal static string Evento_btnPorcomenzar {
            get {
                return ResourceManager.GetString("Evento_btnPorcomenzar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Details.
        /// </summary>
        internal static string Evento_grbDetalles {
            get {
                return ResourceManager.GetString("Evento_grbDetalles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Events.
        /// </summary>
        internal static string Evento_grbEvento {
            get {
                return ResourceManager.GetString("Evento_grbEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subscribe.
        /// </summary>
        internal static string Evento_grbSuscripcion {
            get {
                return ResourceManager.GetString("Evento_grbSuscripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        internal static string Login_btnAceptar {
            get {
                return ResourceManager.GetString("Login_btnAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string login_btncancelar {
            get {
                return ResourceManager.GetString("login_btncancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string Login_contrasenia {
            get {
                return ResourceManager.GetString("Login_contrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registration.
        /// </summary>
        internal static string login_irAregistro {
            get {
                return ResourceManager.GetString("login_irAregistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        internal static string Login_nombreUsuario {
            get {
                return ResourceManager.GetString("Login_nombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a accept.
        /// </summary>
        internal static string Perfi_btnAceptar {
            get {
                return ResourceManager.GetString("Perfi_btnAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Surname.
        /// </summary>
        internal static string Perfil_apellido {
            get {
                return ResourceManager.GetString("Perfil_apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string Perfil_btnDescartar {
            get {
                return ResourceManager.GetString("Perfil_btnDescartar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pay membership.
        /// </summary>
        internal static string Perfil_btnPagarMembresia {
            get {
                return ResourceManager.GetString("Perfil_btnPagarMembresia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string Perfil_nombre {
            get {
                return ResourceManager.GetString("Perfil_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        internal static string Perfil_nombreUsuario {
            get {
                return ResourceManager.GetString("Perfil_nombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Events.
        /// </summary>
        internal static string Principal_btnIrAEventos {
            get {
                return ResourceManager.GetString("Principal_btnIrAEventos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Management.
        /// </summary>
        internal static string Principal_menuGestioDeUsuario {
            get {
                return ResourceManager.GetString("Principal_menuGestioDeUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a language.
        /// </summary>
        internal static string Principal_MenuIdioma {
            get {
                return ResourceManager.GetString("Principal_MenuIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify profile.
        /// </summary>
        internal static string Principal_menuModificarPerfil {
            get {
                return ResourceManager.GetString("Principal_menuModificarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Surname.
        /// </summary>
        internal static string Registro_Apellido {
            get {
                return ResourceManager.GetString("Registro_Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string Registro_btnBorrar {
            get {
                return ResourceManager.GetString("Registro_btnBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        internal static string Registro_btnEnviar {
            get {
                return ResourceManager.GetString("Registro_btnEnviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string Registro_Contrasenia {
            get {
                return ResourceManager.GetString("Registro_Contrasenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string Registro_Nombre {
            get {
                return ResourceManager.GetString("Registro_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        internal static string Registro_NombreDEUsuario {
            get {
                return ResourceManager.GetString("Registro_NombreDEUsuario", resourceCulture);
            }
        }
    }
}
